pipeline {
  agent any
    
  tools {nodejs "node"}
    
  stages {
    stage('Docker Build') {
      agent any
      steps {
        sh 'docker build -t rootwit/wellness:v1 .'
      }
    }
    stage('Docker Push') {
      agent any
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerHub', passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
          sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPassword}"
          sh 'docker tag wellness:v1 rootwit/wellness:v1'
          sh 'docker push rootwit/wellness:v1'
        }
      }
    }

    stage("deploy") {
      steps {
          script {
              echo 'Deploying docker image to EC2'
              def dockerCmd = "docker run -p 8080:8080 -d rootwit/wellness:v1"
          sshagent(['ec2-server']) {
            sh "ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-80-104-242 ${dockerCmd}"
              }
          }
      }
    }


  }
}
